# Generated by Django 4.2.5 on 2024-04-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttovendor',
            name='advance_adjust',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttovendor',
            name='amount_debit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
