# Generated by Django 5.0 on 2024-01-21 08:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholderfund', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHolderFuns',
            fields=[
                ('shf_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_credit', models.FloatField()),
                ('amount_Debit', models.FloatField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('particulars', models.CharField(max_length=100)),
                ('sh_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholderfund.shareholdername')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
