# Generated by Django 5.0 on 2024-01-22 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholderfund', '0003_alter_shareholderfuns_amount_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdcollection',
            name='collection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
