# Generated by Django 5.0 on 2024-01-22 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholderfund', '0004_alter_rdcollection_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdcollection',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
