# Generated by Django 5.0 on 2024-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholderfund', '0006_rdperson_email_rdperson_pan_no_rdperson_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdcollection',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
