# Generated by Django 5.0 on 2024-01-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholderfund', '0008_loancollection_loanperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancollection',
            name='loan_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholderfund.loanperson'),
        ),
    ]
