# Generated by Django 5.0 on 2024-01-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholderfund', '0011_alter_loancollection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loancollection',
            options={},
        ),
    ]
