# Generated by Django 4.2.5 on 2024-03-13 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareholderfund', '0013_loanamount_closing_date_loanamount_opening_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDIntrest',
            fields=[
                ('rd_intrest_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholderfund.rdperson')),
            ],
        ),
        migrations.CreateModel(
            name='RDCollectionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rd_intrest', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shareholderfund.rdintrest')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
