# Generated by Django 4.2.5 on 2024-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholderfund', '0014_rdintrest_rdcollectionnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanamount',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanamount',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanamount',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
