# Generated by Django 4.2.5 on 2024-03-14 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareholderfund', '0015_loanamount_duration_loanamount_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCollectionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('loan_intrest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholderfund.loanamount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
