# Generated by Django 4.2.5 on 2024-01-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_purchaserequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('vendor_name', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
