# Generated by Django 4.2.5 on 2024-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='item_json',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='materia_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='material_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='material_text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
