# Generated by Django 4.2.5 on 2024-01-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='maindata',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
