# Generated by Django 4.2.5 on 2024-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_purchaseorder_maindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('group_no', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('unit_no', models.AutoField(primary_key=True, serialize=False)),
                ('material_umit', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
