# Generated by Django 4.2.5 on 2024-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_materialgroup_materialunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialunit',
            name='materil_unit_desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
