# Generated by Django 4.2.5 on 2024-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_materialunit_materil_unit_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('store_no', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=4)),
                ('store_description', models.CharField(max_length=100)),
            ],
        ),
    ]
