# Generated by Django 5.0 on 2024-01-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreceipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='maindata',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
