# Generated by Django 5.0 on 2024-01-29 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreceipt', '0002_grn_maindata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor_address', models.CharField(default='', max_length=100000)),
                ('delivery_address', models.CharField(default='', max_length=100000)),
                ('item_grn', models.CharField(default='', max_length=1000000)),
                ('billing', models.CharField(default='', max_length=100000)),
                ('maindata', models.CharField(default='', max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
