# Generated by Django 5.0 on 2024-01-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreceipt', '0003_mir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mir',
            name='id',
        ),
        migrations.AddField(
            model_name='mir',
            name='mir_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
