# Generated by Django 5.0 on 2024-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreceipt', '0005_materialissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissue',
            name='remarks',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mir',
            name='mir_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
